version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    # python manage.py makemigrations && python manage.py migrate && 
    container_name: demo
    volumes:
      - .:/demo
    ports:
      - "8000:8000" 